create table companies (
    id bigint generated by default as identity,
    name varchar(255) not null,
    cnpj varchar(14) unique not null,
    enabled boolean not null,
    primary key (id)
    );