create table users (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(255) unique not null,
    password varchar(255) not null,
    enabled boolean not null,
    company_id bigint,
    primary key (id),
    foreign key (company_id) references companies(id) on delete set null
    );