create table users (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(255) unique not null,
    password varchar(255) not null,
    enabled boolean not null,
    client_id bigint,
    primary key (id),
    foreign key (client_id) references clients(id) on delete set null
    );