create table stock_locations (
    id bigint generated by default as identity,
    name varchar(255) not null,
    client_id bigint,
    primary key (id),
    foreign key (client_id) references clients(id) on delete set null
    );