create table stock_locations (
    id bigint generated by default as identity,
    name varchar(255) not null,
    company_id bigint,
    primary key (id),
    foreign key (company_id) references companies(id)
    );