create table unit_measures (
    id bigint generated by default as identity,
    name varchar(15) not null,
    acronym varchar(2) not null,
    company_id bigint,
    primary key (id),
    foreign key (company_id) references companies(id)
    );