create table products (
    id bigint generated by default as identity,
    name varchar(255) not null,
    price numeric(10, 2) not null,
    quantity numeric(10, 3) not null,
    stock_max int not null,
    stock_min int not null,
    unit_measure varchar(50) not null,
    stock_location_id bigint,
    company_id bigint,
    primary key (id),
    foreign key (company_id) references companies(id),
    foreign key (stock_location_id) references stock_locations(id)
    );