create table products (
    id bigint generated by default as identity,
    name varchar(255) not null,
    price numeric(10, 2) not null,
    quantity int not null,
    unit_measure varchar(50) not null,
    stock_location_id bigint,
    client_id bigint,
    primary key (id),
    foreign key (client_id) references clients(id) on delete set null,
    foreign key (stock_location_id) references stock_locations(id) on delete set null
    );