create table movements (
    id bigint generated by default as identity,
    type varchar(50) not null,
    quantity int not null,
    moment date not null,
    note varchar(255),
    product_id bigint,
    stock_location_id bigint,
    user_id bigint,
    client_id bigint,
    primary key (id),
    foreign key (client_id) references clients(id) on delete set null,
    foreign key (product_id) references products(id) on delete set null,
    foreign key (stock_location_id) references stock_locations(id) on delete set null,
    foreign key (user_id) references users(id) on delete set null
    );