create table products (
    id bigint generated by default as identity,
    code varchar(10) not null,
    name varchar(255) not null,
    price numeric(10, 2) not null,
    total_quantity numeric(10, 3) not null,
    stock_max int not null,
    stock_min int not null,
    unit_measure_id bigint not null,
    company_id bigint not null,
    primary key (id),
    foreign key (unit_measure_id) references unit_measures(id),
    foreign key (company_id) references companies(id)
    );