create table movements (
    id bigint generated by default as identity,
    type varchar(20) not null,
    quantity numeric(10, 3) not null,
    moment timestamp with time zone not null,
    note varchar(255),
    product_id bigint not null,
    from_stock_location_id bigint,
    to_stock_location_id bigint,
    user_id bigint not null,
    company_id bigint not null,
    primary key (id),
    foreign key (company_id) references companies(id),
    foreign key (product_id) references products(id),
    foreign key (from_stock_location_id) references stock_locations(id),
    foreign key (to_stock_location_id) references stock_locations(id),
    foreign key (user_id) references users(id)
    );